api/urls.py
from django.urls import path

from api.views import BookReviewAPIView, BookReviewListAPIVIew

app_name = 'api'

urlpatterns = [
    path('reviews/', BookReviewListAPIVIew.as_view(), name='reviews-list'),
    path('review/<int:id>/', BookReviewAPIView.as_view(), name='review-detail')

]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import LandingPage, home_page


urlpatterns = [
    path("", LandingPage.as_view(), name='landing_page'),
    path("home/", home_page, name='home_page'),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api/', include('api.urls')),


    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



users/urls.py
from django.urls import path

from users.views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView
app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logut/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile_edit')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    profile_picture = models.ImageField(default="default_profile_pic.jpg")

users/forms.py
from django import forms

from users.models import CustomUser


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()

        return user


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'profile_picture')

users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from users.forms import UserCreateForm, UserUpdateForm
from django.contrib.auth.forms import AuthenticationForm


class RegisterView(View):
    def get(self, request):
        create_form = UserCreateForm()
        context = {
            "form": create_form
        }
        messages.success(request, 'You have successfully signed up!')
        return render(request, "users/register.html", context)

    def post(self, request):
        create_form = UserCreateForm(data=request.POST)

        if create_form.is_valid():
            create_form.save()
        else:
            context = {
                "form": create_form
            }
            return render(request, "users/register.html", context)

        return redirect('users:login')


class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()

        return render(request, 'users/login.html', {"login_form": login_form})

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)

        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)

            messages.success(request, "You have successfully logged in.")

            return redirect("books:list")
        else:
            return render(request, 'users/login.html', {"login_form": login_form})


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.info(request, "You have successfully logged out.")
        return redirect("landing_page")


class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, "users/profile.html", {"user": request.user})


class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request):
        user_update_form = UserUpdateForm(instance=request.user)
        return render(request, "users/profile_edit.html", {"form": user_update_form})

    def post(self, request):
        user_update_form = UserUpdateForm(
            instance=request.user,
            data=request.POST,
            files=request.FILES
        )
        if user_update_form.is_valid():
            user_update_form.save()
            messages.success(request, "You have successfully updated you profile.")
            return redirect("users:profile")


users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Login page {% endblock title %}

{% block content %}

    <div class="row justify-content-center mt-5 ">
        <div class="col-lg-4 col-md-4 text-center shadow rounded-4 p-3">
            <img class="register_pic" src="{% static 'images/png-transparent-default-avatar.png' %}">
            <form method="post">{% csrf_token %}
                {{ login_form | crispy }}
                <button class="btn btn-primary w-100 mb-4" type="submit">Submit</button>
                <span>No account? Then, <a href="{% url 'users:register' %}">get registred</a></span>
            </form>
        </div>
    </div>

{% endblock content %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% block title %} Profile page {% endblock title %}

{% block content %}

    <div class="container text-center">
        <h1>Profile</h1>
        <img class="img-thumbnail profile-pic" src="{{ user.profile_picture.url }}" alt="Profile picture">

        <div class="p-2">
            <h5>{{ user.first_name }}</h5>
            <h5>{{ user.last_name }}</h5>
            <h5>{{ user.email }}</h5>
        </div>

        <div>
            <a class="btn btn-secondary w-50" href="{% url 'users:profile_edit' %}">Edit profile</a>
        </div>
        <div class="px-2 rounded mt-4 date">
            <span class="join">
                Joined {{ user.date_joined | date:"M d, Y" }}
            </span>
        </div>
    </div>

{% endblock content %}

users/templates/users/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title%} Profile edit {% endblock title%}

{% block content %}


    <div class="row">
        <div class="col-4">
            <h3>Edit profile</h3><hr>
            <form method="post" enctype="multipart/form-data">{% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-primary w-100" type="submit">save changes</button>
            </form>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}



{% block title %} Register page {% endblock title %}

{% block content %}
    <div class="row ">
        <div class="col-lg-4 col-md-4 shadow p-3 rounded-3 mb-3">
            <form class="form-control-sm" method="post" action="{% url 'users:register' %}">{% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-primary w-100 btn-sm" type="submit">Submit</button>
            </form>
        </div>
        <div class="col-md-2">

        </div>
        <div class="col-md-6">
            <img class="img-thumbnail" src="{% static 'images/bookshop-sign-books-store.jpg' %}">
        </div>
    </div>
{% endblock content %}