api/urls.py
from django.urls import path

from api.views import BookReviewAPIView, BookReviewListAPIVIew

app_name = 'api'

urlpatterns = [
    path('reviews/', BookReviewListAPIVIew.as_view(), name='reviews-list'),
    path('review/<int:id>/', BookReviewAPIView.as_view(), name='review-detail')

]

books/urls.py
from django.urls import path
from books.views import BooksView, BookDetailView, AddReviewView, UpdateBookReviewView, \
    ConfirmDeleteReviewView, DeleteReviewView, ComedyBookView, FantasticBookView, \
    DetectiveBookView, AuthorsView, AuthorsDetailView

app_name = 'books'

urlpatterns = [
    path("", BooksView.as_view(), name="list"),
    path("comedy/", ComedyBookView.as_view(), name="comedy-books"),
    path("fantastic/", FantasticBookView.as_view(), name="fantastic-books"),
    path("detective/", DetectiveBookView.as_view(), name="detective-books"),
    path("<int:id>/", BookDetailView.as_view(), name="detail"),
    path("<int:id>/reviews", AddReviewView.as_view(), name="reviews"),
    path("<int:book_id>/reviews/<int:review_id>/edit/", UpdateBookReviewView.as_view(), name="update-reviews"),
    path("<int:book_id>/reviews/<int:review_id>/confirm-delete/",
         ConfirmDeleteReviewView.as_view(), name="confirm-delete-review"),

    path("<int:book_id>/reviews/<int:review_id>/delete/", DeleteReviewView.as_view(), name="delete-review"),

    path('authors/', AuthorsView.as_view(), name='authors'),
    path('authors-detail/<int:id>/', AuthorsDetailView.as_view(), name='authors_detail'),
]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import LandingPage, home_page


urlpatterns = [
    path("", LandingPage.as_view(), name='landing_page'),
    path("home/", home_page, name='home_page'),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api/', include('api.urls')),


    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



users/urls.py
from django.urls import path

from users.views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView
app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logut/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile_edit')
]

templates/base.html
{% load static %}
{% url 'home_page' as home_page_url %}
{% url 'books:list' as book_list_url %}
{% url 'books:comedy-books' as comedy_list_url %}
{% url 'books:fantastic-books' as fantasy_list_url %}
{% url 'books:detective-books' as detective_list_url %}

{% url 'users:profile' as profile_page_url %}
{% url 'users:profile_edit' as profile_edit_page %}
{% url 'books:authors' as author_url %}
{% url 'landing_page' as main_page_url %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Goodreads clone {% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/rateyo@2.3.2/dist/jquery.rateyo.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/flickity/1.0.0/flickity.css'>

    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link href="{% static "css/main.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/cards.css" %}" rel="stylesheet" type="text/css">
</head>

<body class="mx-3">

<div class="container-fluid">

    <nav class="navbar navbar-expand-lg mb-5 ">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'landing_page' %}">Goodreads clone</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == home_page_url %} active {% endif %}"
                           aria-current="page"
                           href="{{ home_page_url }}">Reviews</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == book_list_url or request.path == comedy_list_url or request.path == fantasy_list_url or request.path == detective_list_url %} active {% endif %}"
                           aria-current="page"
                           href="{{ book_list_url }}">Books</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == author_url %} active {% endif %}"
                           aria-current="page"
                           href="{{ author_url }}">Authors</a>
                    </li>
                </ul>

                <div class="me-5">
                    {% if request.user.is_authenticated %}
                        <ul class="navbar-nav me-5">
                            <li class="nav-item dropdown-center">
                                <a class="nav-link dropdown-toggle {% if request.path == profile_page_url or request.path == profile_edit_page %} active {% endif %}"
                                   href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    {{ request.user.username }}
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item " href="{{ profile_page_url }}">Profile</a></li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="{% url 'users:logout' %}">Log out</a></li>
                                </ul>
                            </li>
                        </ul>
                    {% else %}
                        <p><a class="btn btn-dark btn-sm" href="{% url 'users:login' %}">Login</a></p>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>

    <div class="row custom-nav mb-5">
        <div class="col-md-8">
            <ul class="nav">
                <li class="nav-item {% if request.path == book_list_url %}active-category{% endif %}">
                    <a class="nav-link custom-nav-link" href="{{ book_list_url }}">All</a>
                </li>
                <li class="nav-item {% if request.path == comedy_list_url %}active-category{% endif %}">
                    <a class="custom-nav-link nav-link" href="{{ comedy_list_url }}">Comedy</a>
                </li>
                <li class="nav-item {% if request.path == fantasy_list_url %}active-category{% endif %}">
                    <a class="custom-nav-link nav-link" href="{{ fantasy_list_url }}">Fantasy</a>
                </li>
                <li class="nav-item {% if request.path == detective_list_url %}active-category{% endif %}">
                    <a class="custom-nav-link nav-link" href="{{ detective_list_url }}">Detective</a>
                </li>
            </ul>
        </div>
        <div class="col-md-4">
            {% if request.path == book_list_url or request.path == comedy_list_url or request.path == fantasy_list_url or request.path == detective_list_url %}
                <form class="d-flex" method="get">
                    <input class="form-control me-2" type="text" placeholder="search" name="q"
                           value="{{ search_query }}">
                    <button type="submit" class="btn btn-secondary btn-sm">Search</button>
                </form>
            {% endif %}
        </div>
    </div>

    <div class="container-fluid">
        {% if messages %}
            <div class="mt-3">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        {% block content %}

        {% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/rateyo@2.3.2/dist/jquery.rateyo.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
            crossorigin="anonymous"></script>

    <script src='https://cdnjs.cloudflare.com/ajax/libs/flickity/1.0.0/flickity.pkgd.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src="{% static 'js/cards.js' %}"></script>

</div>

</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Home page {% endblock title %}

{% block content %}
    <h2 class="text-center">All reviews</h2>
    <hr>

    <div class="cards">
        {% for review in page_obj %}
            <div class="card mb-5">
                <div class="card__image-holder">
                    <img class="card__image " src="{{ review.book.cover_picture.url }}" alt="wave"/>
                </div>
                <div class="card-title">
                    <a href="#" class="toggle-info btn">
                        <span class="left"></span>
                        <span class="right"></span>
                    </a>
                    <h2>
                        <img src="{{ review.user.profile_picture.url }}" class="d-block ui-w-40 rounded-circle"
                             alt="profile pic">
                        <b>{{ review.user.username }}</b>
                    </h2>
                    rated this book {{ review.stars_given }} stars
                    <div class="text-muted small">{{ review.created_at }}</div>
                </div>
                <div class="card-flap flap1">
                    <div class="card-description">
                        {{ review.comment | truncatechars:300 }}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination pagination-sm">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
            {% endif %}

            {% for i in page_obj.paginator.page_range %}
                <li class="page-item {% if i == page_obj.number %}active{% endif %}">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock content %}

templates/landing.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <!-- partial:index.partial.html -->
    <div class="book-store">

        <div class="book-slide">
            <div class="book js-flickity" data-flickity-options='{ "wrapAround": true, "autoPlay": true, "pauseAutoPlayOnHover": true }'>
                {% for book in books|slice:":6" %}
                    <div class="book-cell">
                        <div class="book-img">
                            <a href="{% url 'books:detail' book.id %}">
                                <img src="{{ book.cover_picture.url }}" alt="{{ book.title }}" class="book-photo">
                            </a>
                        </div>
                        <div class="book-content">
                            <div class="book-title">{{ book.title }}</div>
                            <div class="book-author">{{ book.book_author }}</div>
{#                            <div class="rate">#}
{#                                <fieldset class="rating">#}
{#                                    <input type="checkbox" id="star5" name="rating" value="5"/>#}
{#                                    <label class="full" for="star5"></label>#}
{#                                    <input type="checkbox" id="star4" name="rating" value="4"/>#}
{#                                    <label class="full" for="star4"></label>#}
{#                                    <input type="checkbox" id="star3" name="rating" value="3"/>#}
{#                                    <label class="full" for="star3"></label>#}
{#                                    <input type="checkbox" id="star2" name="rating" value="2"/>#}
{#                                    <label class="full" for="star2"></label>#}
{#                                    <input type="checkbox" id="star1" name="rating" value="1"/>#}
{#                                    <label class="full" for="star1"></label>#}
{#                                </fieldset>#}
{#                                <span class="book-voters">1.987 voters</span>#}
{#                            </div>#}
                            <div class="book-sum">{{ book.description | truncatewords:18 }}</div>
                            <div class="book-see"><a class="text-secondary text-decoration-none" href="{% url 'books:detail' book.id %}">
                                See The Book
                            </a> </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="main-wrapper">
            <div class="books-of">
                <div class="week">
                    <div class="author-title">Authors</div>
                    {% for author in authors|slice:":20" %}
                        <div class="author">
                            <img src="{{ author.picture.url }}"
                                 alt="" class="author-img">
                            <div class="author-name">
                                <a class="author-name" href="{% url 'books:authors_detail' author.id %}">{{ author.first_name }} {{ author.last_name }}</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="overlay"></div>
            </div>

            <div class="popular-books">
                <div class="main-menu">
                    <div class="genre">Latest books</div>
                </div>
                <div class="book-cards">
                    {% for book in books|slice:":20" %}
                        <div class="book-card">
                            <div class="content-wrapper">
                                <img src="{{ book.cover_picture.url }}" alt="" class="book-card-img">
                                <div class="card-content">
                                    <div class="book-name">{{ book.title }}</div>
                                    <div class="book-by">by {{ book.book_author }}</div>
                                    <div class="rate">

                                    </div>
                                    <div class="book-sum card-sum">
                                        {{ book.description }}
                                    </div>
                                    <div class="likes">
                                        <a class="detail-view" href="{% url 'books:detail' book.id %}">
                                            ...view detail
                                        </a>
                                    </div>
                                </div>
                            </div>

                        </div>
                    {% endfor %}
                </div>

            </div>

        </div>

    </div>

    <!-- partial -->

{% endblock content %}