api/urls.py
from django.urls import path

from api.views import BookReviewAPIView, BookReviewListAPIVIew

app_name = 'api'

urlpatterns = [
    path('reviews/', BookReviewListAPIVIew.as_view(), name='reviews-list'),
    path('review/<int:id>/', BookReviewAPIView.as_view(), name='review-detail')

]

books/urls.py
from django.urls import path
from books.views import BooksView, BookDetailView, AddReviewView, UpdateBookReviewView, \
    ConfirmDeleteReviewView, DeleteReviewView, ComedyBookView, FantasticBookView, \
    DetectiveBookView, AuthorsView, AuthorsDetailView

app_name = 'books'

urlpatterns = [
    path("", BooksView.as_view(), name="list"),
    path("comedy/", ComedyBookView.as_view(), name="comedy-books"),
    path("fantastic/", FantasticBookView.as_view(), name="fantastic-books"),
    path("detective/", DetectiveBookView.as_view(), name="detective-books"),
    path("<int:id>/", BookDetailView.as_view(), name="detail"),
    path("<int:id>/reviews", AddReviewView.as_view(), name="reviews"),
    path("<int:book_id>/reviews/<int:review_id>/edit/", UpdateBookReviewView.as_view(), name="update-reviews"),
    path("<int:book_id>/reviews/<int:review_id>/confirm-delete/",
         ConfirmDeleteReviewView.as_view(), name="confirm-delete-review"),

    path("<int:book_id>/reviews/<int:review_id>/delete/", DeleteReviewView.as_view(), name="delete-review"),

    path('authors/', AuthorsView.as_view(), name='authors'),
    path('authors-detail/<int:id>/', AuthorsDetailView.as_view(), name='authors_detail'),
]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import LandingPage, home_page


urlpatterns = [
    path("", LandingPage.as_view(), name='landing_page'),
    path("home/", home_page, name='home_page'),
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api/', include('api.urls')),


    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



books/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone

from users.models import CustomUser


class Categories(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)
    description = models.TextField()
    isbn = models.CharField(max_length=17)
    cover_picture = models.ImageField(upload_to='media-files/books', default="default_cover.jpg")

    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    picture = models.ImageField(upload_to='media-files/authors', default="default_profile_pic.jpg")
    email = models.EmailField()
    bio = models.TextField()

    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return f"{self.first_name} - {self.last_name}"


class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return self.book.title


class BookReview(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.TextField()
    stars_given = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    created_at = models.DateTimeField(default=timezone.now)


books/forms.py
from django import forms
from books.models import BookReview


class BookReviewForm(forms.ModelForm):
    stars_given = forms.IntegerField(min_value=1, max_value=5)

    class Meta:

        model = BookReview
        fields = ('stars_given', 'comment')

books/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView

from books.forms import BookReviewForm
from books.models import Book, BookReview, Categories, BookAuthor, Author


# class BooksView(ListView):
#     template_name = "books/list.html"
#     queryset = Book.objects.all()
#     context_object_name = "books"
#     paginate_by = 3


class AuthorsView(View):
    def get(self, request):
        authors = Author.objects.all().order_by('-id')

        context = {
            'authors': authors
        }
        return render(request, 'authors/authors_list.html', context)


def search_books(query):
    books = Book.objects.filter(title__icontains=query)
    return books


class AuthorsDetailView(View):
    def get(self, request, id):
        author = Author.objects.get(id=id)
        books_by_author = Book.objects.filter(bookauthor__author=author)

        context = {
            'author': author,
            'books_by_author': books_by_author
        }
        return render(request, 'authors/authors_detail.html', context)


class BooksView(View):
    def get(self, request):
        book_author = BookAuthor
        categories = Categories.objects.all()
        search_query = request.GET.get('q', '')
        books = search_books(search_query) if search_query else Book.objects.all().order_by('id')

        page_size = request.GET.get("page_size", 4)
        paginator = Paginator(books, page_size)

        page_num = request.GET.get("page", 1)
        page_obj = paginator.get_page(page_num)

        context = {
            'categories': categories,
            'page_obj': page_obj,
            'search_query': search_query
        }

        return render(request, "books/list.html", context)


class ComedyBookView(ListView):
    template_name = 'books/comedy.html'
    context_object_name = 'comedy_books'
    paginate_by = 3

    def get_queryset(self):
        search_query = self.request.GET.get('q', '')
        return search_books(search_query) if search_query else Book.objects.filter(category_id=1)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Categories.objects.all()
        context['search_query'] = self.request.GET.get('q', '')
        return context


class FantasticBookView(ListView):
    template_name = 'books/fantastic.html'
    context_object_name = 'fantastic_books'
    paginate_by = 3

    def get_queryset(self):
        search_query = self.request.GET.get('q', '')
        return search_books(search_query) if search_query else Book.objects.filter(category_id=2)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Categories.objects.all()
        context['search_query'] = self.request.GET.get('q', '')
        return context


class DetectiveBookView(ListView):
    template_name = 'books/detective.html'
    context_object_name = 'detective_books'
    paginate_by = 3

    def get_queryset(self):
        search_query = self.request.GET.get('q', '')
        return search_books(search_query) if search_query else Book.objects.filter(category_id=3)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Categories.objects.all()
        context['search_query'] = self.request.GET.get('q', '')
        return context


# class BookDetailView(DetailView):
#     template_name = "books/detail.html"
#     pk_url_kwarg = "id"
#     model = Book


class BookDetailView(View):
    def get(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewForm()
        context = {
            "book": book,
            "review_form": review_form
        }
        return render(request, "books/detail.html", context)


class AddReviewView(LoginRequiredMixin, View):
    def post(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewForm()

        if request.method == 'POST':
            review_form = BookReviewForm(request.POST)
            if review_form.is_valid():
                BookReview.objects.create(
                    book=book,
                    user=request.user,
                    stars_given=review_form.cleaned_data['stars_given'],
                    comment=review_form.cleaned_data['comment']
                )
                return redirect(reverse("books:detail", kwargs={"id": book.id}))

        return render(request, "books/detail.html", {"book": book, "review_form": review_form})


class UpdateBookReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_form = BookReviewForm(instance=review)
        context = {
            "book": book,
            "review": review,
            "review_form": review_form,
        }
        return render(request, "books/edit_review.html", context)

    def post(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_form = BookReviewForm(data=request.POST, instance=review)

        if review_form.is_valid():
            review_form.save()
            return redirect(reverse("books:detail", kwargs={"book_id": book.id}))

        context = {
            "book": book,
            "review": review,
            "review_form": review_form,
        }
        return render(request, "books/edit_review.html", context)


class ConfirmDeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        context = {
            'book': book,
            'review': review
        }
        return render(request, "books/confirm_delete_review.html", context)


class DeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)

        review.delete()
        messages.success(request, "You have successfully deleted this review")

        return redirect(reverse("books:detail", kwargs={"id": book_id}))

books/templates/books/comedy.html
{% extends 'base.html' %}

{% block title %}Books page{% endblock title %}

{% block content %}


    <div class="book-cards mb-5" id="book-cards">
        {% if comedy_books %}
            {% for comedy_book in comedy_books %}
                <div class="book-card" data-category="{{ comedy_book.category }}">
                    <div class="content-wrapper">
                            <img src="{{ comedy_book.cover_picture.url }}" alt="" class="book-card-img">
                        <div class="card-content">
                            <div class="book-name">{{ comedy_book.title }}</div>
                            <div class="book-by">by {{ comedy_book.book_author }}</div>
{#                            <div class="rate">#}
{#                                <fieldset class="rating book-rate">#}
{#                                    <input type="checkbox" id="star-c1" name="rating" value="5">#}
{#                                    <label class="full" for="star-c1"></label>#}
{#                                    <input type="checkbox" id="star-c2" name="rating" value="4">#}
{#                                    <label class="full" for="star-c2"></label>#}
{#                                    <input type="checkbox" id="star-c3" name="rating" value="3">#}
{#                                    <label class="full" for="star-c3"></label>#}
{#                                    <input type="checkbox" id="star-c4" name="rating" value="2">#}
{#                                    <label class="full" for="star-c4"></label>#}
{#                                    <input type="checkbox" id="star-c5" name="rating" value="1">#}
{#                                    <label class="full" for="star-c5"></label>#}
{#                                </fieldset>#}
{#                                <span class="book-voters card-vote">1.987 voters</span>#}
{#                            </div>#}
                            <div class="book-sum card-sum">
                                {{ comedy_book.description }}
                            </div>
                            <a class="detail-view" href="{% url 'books:detail' comedy_book.id %}">
                                ...view detail
                            </a>
                        </div>
                    </div>

                </div>
            {% endfor %}
        {% else %}
            <p>No comedy books found.</p>
        {% endif %}
    </div>



    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
            {% endif %}

            {% for i in page_obj.paginator.page_range %}
                <li class="page-item {% if i == page_obj.number %}active{% endif %}">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                </li>
            {% endif %}
        </ul>
    </nav>


{% endblock content %}

books/templates/books/confirm_delete_review.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Confirm delete {% endblock title %}

{% block content %}
    <h3>Are you sure to delete this review?</h3>
    <p><b>Book:</b> {{ book.title }}</p>
    <p><b>Comment:</b> {{ review.comment }}</p>

    <form method="get" action="detail.html">
        <a href="{% url 'books:delete-review' book.id review.id %}" class="btn btn-outline-success" type="submit">Yes</a>
        <a  href="{% url 'books:detail' book.id %}" class="btn btn-outline-danger" type="submit">No</a>
    </form>

{% endblock content %}

books/templates/books/detail.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% block title %} Book detail page{% endblock title %}

{% block content %}

    <div class="row  shadow mb-3 p-3">
        <div class="row">
            <div class="col-3">
                <img class="cover-pic img img-thumbnail" src="{{ book.cover_picture.url }}" style="float: right"
                     alt="cover image">
            </div>
            <div class="col-9 ">
                <h2>{{ book.title }}</h2>
                <div class="mb-2">
                        <span class="fst-italic mb-3">
                            Authored by:
                            {% for book_author in book.bookauthor_set.all %}
                                <a class="text-decoration-none"
                                   href="{% url 'books:authors_detail' book_author.author.id %}">
                                {{ book_author.author.full_name }}
                                 </a>
                                {% if not forloop.last %},{% endif %}
                            {% endfor %}
                        </span><hr>

                </div>
                <p>{{ book.description }}</p>
            </div>
        </div>

    </div>
    <div class="col-md-6">
        <form method="post" action="{% url 'books:reviews' book.id %}">
            {% csrf_token %}
            <div class="rate">
                <fieldset class="rating mb-3">
                    <input type="radio" id="star5" name="stars_given" value="5"/>
                    <label class="full" for="star5"></label>
                    <input type="radio" id="star4" name="stars_given" value="4"/>
                    <label class="full" for="star4"></label>
                    <input type="radio" id="star3" name="stars_given" value="3"/>
                    <label class="full" for="star3"></label>
                    <input type="radio" id="star2" name="stars_given" value="2"/>
                    <label class="full" for="star2"></label>
                    <input type="radio" id="star1" name="stars_given" value="1"/>
                    <label class="full" for="star1"></label>
                </fieldset>
            </div>
            <textarea class="w-100 mb-3" name="comment" rows="5" cols="40"></textarea>
            <button class="btn btn-success btn-sm" type="submit">Добавить отзыв</button>
        </form>
    </div>
    <hr>

    {% if book.bookreview_set.exists %}
        <h4 class="mb-3">- Reviews -</h4>

        {% for review in book.bookreview_set.all %}
            <div class="row mb-4">
                <div class="col-1">
                    <img class="profile-pic_review" src="{{ review.user.profile_picture.url }}"
                         alt="comment profile picture">
                </div>
                <div class="col-10">
                    <b>{{ review.user.username|upper }}</b>

                    <span class="fw-lighter">{{ review.created_at }}</span>
                    {% if review.user == request.user %}
                        <a href="{% url 'books:update-reviews' book.id review.id %}"><i
                                class="bi bi-pencil-square"></i></a> |
                        <a href="{% url 'books:confirm-delete-review' book.id review.id %}"><i
                                class="bi bi-trash3-fill"></i></a>
                    {% endif %}
                    <p class="font-monospace fs-6">
                        - {{ review.comment }}
                    </p>
                </div>
            </div>
        {% endfor %}
    {% endif %}


{% endblock content %}

books/templates/books/detective.html
{% extends 'base.html' %}

{% block title %}Detective{% endblock title %}

{% block content %}




    <div class="book-cards mb-5" id="book-cards">
        {% if detective_books %}
            {% for detective_book in detective_books %}
                <div class="book-card" data-category="{{ detective_book.category }}">
                    <div class="content-wrapper">
                        <img src="{{ detective_book.cover_picture.url }}" alt="" class="book-card-img">
                        <div class="card-content">
                            <div class="book-name">{{ detective_book.title }}</div>
                            <div class="book-by">by {{ detective_book.book_author }}</div>
                            {#                            <div class="rate">#}
                            {#                                <fieldset class="rating book-rate">#}
                            {#                                    <input type="checkbox" id="star-c1" name="rating" value="5">#}
                            {#                                    <label class="full" for="star-c1"></label>#}
                            {#                                    <input type="checkbox" id="star-c2" name="rating" value="4">#}
                            {#                                    <label class="full" for="star-c2"></label>#}
                            {#                                    <input type="checkbox" id="star-c3" name="rating" value="3">#}
                            {#                                    <label class="full" for="star-c3"></label>#}
                            {#                                    <input type="checkbox" id="star-c4" name="rating" value="2">#}
                            {#                                    <label class="full" for="star-c4"></label>#}
                            {#                                    <input type="checkbox" id="star-c5" name="rating" value="1">#}
                            {#                                    <label class="full" for="star-c5"></label>#}
                            {#                                </fieldset>#}
                            {#                                <span class="book-voters card-vote">1.987 voters</span>#}
                            {#                            </div>#}
                            <div class="book-sum card-sum">
                                {{ detective_book.description }}
                            </div>
                            <a class="detail-view" href="{% url 'books:detail' detective_book.id %}">
                                ...view detail
                            </a>
                        </div>
                    </div>

                </div>
            {% endfor %}
        {% else %}
            <p>No detective books found.</p>
        {% endif %}
    </div>



    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
            {% endif %}

            {% for i in page_obj.paginator.page_range %}
                <li class="page-item {% if i == page_obj.number %}active{% endif %}">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                </li>
            {% endif %}
        </ul>
    </nav>


{% endblock content %}

books/templates/books/edit_review.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Edit reviews {% endblock title %}

{% block content %}
    <h3>Edit reviews</h3>
    <div class="row mb-4">
        <div class="col-6">
            <form method="post" action="{% url 'books:reviews' book.id %}">
    {% csrf_token %}
    <div class="rate">
        <fieldset class="rating mb-3">
            <input type="radio" id="star5" name="stars_given" value="5"/>
            <label class="full" for="star5"></label>
            <input type="radio" id="star4" name="stars_given" value="4"/>
            <label class="full" for="star4"></label>
            <input type="radio" id="star3" name="stars_given" value="3"/>
            <label class="full" for="star3"></label>
            <input type="radio" id="star2" name="stars_given" value="2"/>
            <label class="full" for="star2"></label>
            <input type="radio" id="star1" name="stars_given" value="1"/>
            <label class="full" for="star1"></label>
        </fieldset>
    </div>
    <textarea class="w-100 mb-3" name="comment" rows="5" cols="40"></textarea>
    <button class="btn btn-success btn-sm" type="submit">Добавить отзыв</button>
</form>

        </div>
    </div>
{% endblock content %}

books/templates/books/fantastic.html
{% extends 'base.html' %}

{% block title %}Books page{% endblock title %}

{% block content %}


    <div class="book-cards mb-5" id="book-cards">
        {% if fantastic_books %}
            {% for fantastic_book in fantastic_books %}
                <div class="book-card" data-category="{{ fantastic_book.category }}">
                    <div class="content-wrapper">
                            <img src="{{ fantastic_book.cover_picture.url }}" alt="" class="book-card-img">
                        <div class="card-content">
                            <div class="book-name">{{ fantastic_book.title }}</div>
                            <div class="book-by">by {{ fantastic_book.book_author }}</div>
{#                            <div class="rate">#}
{#                                <fieldset class="rating book-rate">#}
{#                                    <input type="checkbox" id="star-c1" name="rating" value="5">#}
{#                                    <label class="full" for="star-c1"></label>#}
{#                                    <input type="checkbox" id="star-c2" name="rating" value="4">#}
{#                                    <label class="full" for="star-c2"></label>#}
{#                                    <input type="checkbox" id="star-c3" name="rating" value="3">#}
{#                                    <label class="full" for="star-c3"></label>#}
{#                                    <input type="checkbox" id="star-c4" name="rating" value="2">#}
{#                                    <label class="full" for="star-c4"></label>#}
{#                                    <input type="checkbox" id="star-c5" name="rating" value="1">#}
{#                                    <label class="full" for="star-c5"></label>#}
{#                                </fieldset>#}
{#                                <span class="book-voters card-vote">1.987 voters</span>#}
{#                            </div>#}
                            <div class="book-sum card-sum">
                                {{ fantastic_book.description }}
                            </div>
                            <a class="detail-view" href="{% url 'books:detail' fantastic_book.id %}">
                                ...view detail
                            </a>
                        </div>
                    </div>

                </div>
            {% endfor %}
        {% else %}
            <p>No fantastic books found.</p>
        {% endif %}
    </div>



    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
            {% endif %}

            {% for i in page_obj.paginator.page_range %}
                <li class="page-item {% if i == page_obj.number %}active{% endif %}">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                </li>
            {% endif %}
        </ul>
    </nav>


{% endblock content %}